name-template: 'v$NEXT_PATCH_VERSION' # 次バージョンのタグ名をタイトルに設定
tag-template: 'v$NEXT_PATCH_VERSION' # 次バージョンのタグ名を設定
exclude-labels: # 対象のラベルが付与されてるPRは、リリース内容に乗せない
  - 'release'
categories: # 対象ラベルに一致したら、セクション分けてくれる
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'bugfix'
  - title: 'Maintenance'
    labels:
      - 'chore'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR' # PR情報のテンプレート
template: | # リリースの内容テンプレート
  ## Changes
  $CHANGES