version: "3.9"

volumes:
  php-fpm-socket:
  db-store:
  db-logs-store:

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./src
        target: /var/www/

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm/
        volume:
          nocopy: true
      - type: bind
        source: ./src
        target: /var/www/
    restart: always

  db:
    image: mysql:8.0
    container_name: database
    ports:
      -  "3308:3306"
    volumes:
      -  ./docker/db/my.conf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}

  redis:
    image: "redis:latest"
    container_name: redis